### ISSUE TITLE
なぜ、インド？

### ISSUE THREAD

**Issue by MotoyaTakashi** [MotoyaTakashi/connected-onestop-in-gov-info#1]
はじめに.md

※なぜ、インド？ １．一度、行政サービスが出来上がった後のデジタル変革は 　　とても難しい。（アナログ行政との比較、）⇒インド 　アメリカ、日本←困難。韓国、フィンランド（恩恵享受のため←やりやすい） ↑スポット

２．日本の自治体職員が、インドの歩んだ創り上げた 行政サービスへのデジタルサービス適用に希望が持てるように。

３．インドがアドホック、右往左往して進んできた道（日本は伸びしろがある。） ※やり方はある。 　国、広域への集中、あるいは、活動委任、承認とか。

西山さんと議論した時の話としては、日本のデジタル化に落とした時に、インディアスタックがどういった対応関係ではまるのかのイメージがつかないことが理解が得られにくいポイントであるとわかったと言ってました。

デジタル遺産。銀行口座とか。1回きり。 東京都、子供ＤＸ。

コンセントマネージャ（旧：情報バンク） 希望される方。

**Comment by tek528** [comment]
＞一度、行政サービスが出来上がった後のデジタル変革は とても難しい。
日本とインドの行政サービスの細かさの比較資料があるか探してみます。
